name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Setup Go Tools
        run: make tools

      - name: Check Formatting
        run: make fmtcheck

      - name: Vet Code
        run: make vet

      # skip there is a bug in https://github.com/bflad/tfproviderlint/issues/255
      #- name: Lint Code
      #  run: make lint

      - name: Check Build
        run: make build

      - name: Test
        run: make test

      - name: Run VCR smoke tests
        run: make smoke-test-play-vcr-acc